### PR TITLE
Fix to the issue "QuerySnapshot.docChanges has been changed from a property into a method"

### PR DESCRIPTION
**Pull request by Vanluren**
My attempt at fixing issue:#29.

As this is my first OSS pull request, I probably haven't done everything correctly. All feedback is very warmly welcomed ;-)

### CODE REVIEW

**Comment by samtstern** [comment]
@Vanluren just FYI the build is failing due to linting:
>   39:27  error  Strings must use singlequote  quotes

**Comment by samtstern** [comment]
@Vanluren I think I may have led you in the wrong direction here, sorry about that!  

These code changes should be made in the codelab document, right?  Otherwise we're putting the completed code into the starter project!

If you agree with me I am happy to take the code you've written here and update the codelab snippets (unfortunately you can't do that using a pull request due to how our codelabs system works)

**Comment by Vanluren** [comment]
Yep, this is the code in the codelab! Use it where ever you want 👍

**Comment by samtstern** [comment]
@Vanluren published your fix here!
https://codelabs.developers.google.com/codelabs/firestore-web/#5

Thanks for doing this.

**Pull request closed without merging**
