### PR TITLE
add docs to repo

### PR DESCRIPTION
**Pull request by kroikie**
Add documentation for this codelab to the repository. This will allow updates to the prose of the codelab to be done via this repository.

The claat tool can be used to preview the changes. Two commands are required to view changes:

claat export -f html docs/index.md
claat serve
The preview would be available in the flutter-firebase directory.

### CODE REVIEW

**Comment by nicolasgarnier** [comment]
Hey @kroikie, this looks cool. How do you publish the document? I'm wondering if there is a way we could automate publishing the document as soon as changes are merged into master.

**Comment by samtstern** [comment]
@nicolasgarnier we can't yet publish from markdown, only stage.  Right now this is hopes and dreams status.

**Comment by nicolasgarnier** [comment]
😭 
Then, is there a reason we're adding this at this point? If I want to update the codelab I'll need to make sure both the docs and the markdown are updated, looks like more work no?

**Comment by nicolasgarnier** [comment]
FYI the instructions have been changed in the mean time and this would need to be re-generated.

**Pull request closed without merging**
